export class Selectables {
  categories: [
    'Cocktails',
    'American',
    'Asian Fusion',
    'Avant-garde Cuisine',
    'Bar',
    'Brasa',
    'Breakfast & brunch',
    'Burger & sandwich',
    'Café',
    'Cake & pastry',
    'Caribbean',
    'Chinese',
    'Craft beer',
    'French',
    'Healthy',
    'Ice cream',
    'Italian',
    'Japanese',
    'Korean',
    'Mexican',
    'Peruvian',
    'Pizza',
    'Ramen',
    'Seafood',
    'South American',
    'Speciality Coffee',
    'Sushi',
    'Tapas',
    'Thai',
    'Vermut',
    'Vietnamese',
    'Wine'];
}
